# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish to modrinth and curseforge

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew remapJar
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: pNabrMMw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 459929
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: fabric
          game-versions: 1.18.1
          dependencies: |
            cloth-config | depends
            fabric-api | depends
            applied-energistics-2 | depends
            roughly-enough-items | suggests
            trinkets-fabric | suggests
          java: 17
          version: ${{ github.event.release.tag_name }}-fabric
          name: ${{ github.event.release.tag_name }}-fabric
          files-primary: fabric/build/libs/!(*-@(dev|dev-shadow)).jar
          files-secondary: ""

      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: pNabrMMw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 459929
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          loaders: forge
          game-versions: 1.18.1
          dependencies: |
            cloth-config | depends
            applied-energistics-2 | depends
            architectury-forge | depends
          java: 17
          version: ${{ github.event.release.tag_name }}-forge
          name: ${{ github.event.release.tag_name }}-forge
          files-primary: forge/build/libs/!(*-@(dev|dev-shadow)).jar
          files-secondary: ""